using System;
using System.Collections;

public class Program
{
    private static void Main(string[] args)
    {
        // Console.WriteLine("Problem 1");
        //  Problem1();

        // Console.WriteLine("Problem 2");
        //    Problem2();

        // Console.WriteLine("Problem 3");
        //Problem3();

        // Console.WriteLine("Problem 4");
        // Problem4();

        //Console.WriteLine("Problem 5");
        //Problem5();

        //Console.WriteLine("Problem 6");
       // Problem6();
        Console.WriteLine("Problem 7");
        Problem7();
    }

    //
    // Print all odd numbers from 20 to 1
    //
    public static void Problem1()
    {
        for (int i = 20; i >= 1; i--)
        {
            if (i % 2 == 1)
            {
                Console.WriteLine(i);
            }
        }
    }

    // find odd numbers from 33 to 1
    public static void Problem2()
    {
        for (int i = 33; i >= 1; i--)
        {
            if (i % 2 == 1)
            {
                Console.WriteLine(i);
            }
        }
    }

    //
    // If we list all the natural numbers below 10 that are multiples of 3 or 5, we get 3, 5, 6 and 9.
    // The sum should be multiples is 23.
    // Find the sum of all multiples of 3 or 5 below 100.

    public static void Problem3()
    {
        var sum = 0;
        for (int i = 0; i < 100; i++)
        {
            if (i % 3 == 0 || i % 5 == 0)
            {
                sum += i;
            }
        }
        Console.WriteLine(sum);
    }

    //Homework 1- Write a program that reads a number from the keyboard. Check whether that number is divisible by 7 and 11 or not.

    public static void Problem4()
    {
        int input = Convert.ToInt32(Console.ReadLine());
        if (input % 7 == 0)
        {
            Console.WriteLine("Input is divisible by 7");
        }
        else if (input % 11 == 0)
        {
            Console.WriteLine("Input is divisible by 11");
        }
        else
        {
            Console.WriteLine("Input not divisible by 7 or 11");
        }
    }

    //Homework 2- Check whether a given year is leap year or not.

    public static void Problem5()
    {
        int year = Convert.ToInt32(Console.ReadLine());
        if (year % 4 == 0)
        {
            Console.WriteLine("Year is leap!");
        }
        else
        {
            Console.WriteLine("Year is not leap!");
        }
    }

    //Homework 3- By listing the first six prime numbers: 2, 3, 5, 7, 11, and 13, we can see that the 6th prime is 13. What is the 47th prime number?
    public static void Problem6()
    {
        int count = 0; // count the number of prime numbers found
        int n = 2; // start with the first prime number

        while (count <= 47)
        {
            bool isPrime = true;

            for (int i = 2; i < n; i++)
            {
                if (n % i == 0)
                {
                    isPrime = false;
                    break;
                }
            }

            if (isPrime)
            {
                count++;
            }

            if (count == 47)
            {
                Console.WriteLine(n);
                break;
            }
            n++; 
        }

    }

    //Homework 4- Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
    //By considering the terms in the Fibonacci sequence whose values do not exceed 1000, find the sum of the even-valued terms.
    public static void Problem7()
    {
        int maxVal = 1000;
        int prevTerm = 1;
        int currTerm = 2;
        int sumEven = 0;

        while (currTerm <= maxVal)
        {
            if (currTerm % 2 == 0)
            {
                sumEven += currTerm;
            }

            int nextTerm = prevTerm + currTerm;
            prevTerm = currTerm;
            currTerm = nextTerm;
        }

        Console.WriteLine("Sum of even-valued terms in the Fibonacci sequence up to " + maxVal + " is " + sumEven);
    }
  
}